CREATE DATABASE CADASTRO;
;;
use CADASTRO
;;
CREATE TABLE IF NOT EXISTS CONTATO (
NOME VARCHAR(20),
TELEFONE VARCHAR(9),
DATA_NASC DATE,
EMAIL VARCHAR(30)
)ENGINE=MyISAM; 
;;
INSERT INTO CONTATO (NOME,TELEFONE,DATA_NASC,EMAIL) VALUES('IGOR FRAZZON', '981447368','1984-01-15','igor.frazzon@gmail.com');
