CREATE DATABASE CADASTRO;
;;
use CADASTRO
;;
CREATE TABLE IF NOT EXISTS CONTATO (
NOME VARCHAR(20),
TELEFONE VARCHAR(9),
DATA_NASC DATE,
EMAIL VARCHAR(30)
)ENGINE=MyISAM; 
;;
INSERT INTO CONTATO (NOME,TELEFONE,DATA_NASC,EMAIL) VALUES('JORGE SILVA, '981447654','981447654','jorge@gmail.com');
